language: node_js
node_js:
  - '5'
  - '4'

branches:
  only:
  - master

install:
  - gem install jekyll html-proofer
  - npm install

script: npm run travis

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
