language: node_js
node_js:
  - '5'
  - '4'

branches:
  only:
  - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - rvm install 2.1
  - ruby -v

install:
  - npm install
  - gem install jekyll html-proofer

script: jekyll build && htmlproofer ./_site

sudo: false
